### ISSUE TITLE
Decrease sensor sample period from 20ms to 5ms

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/frc-characterization#116]
This will better capture acceleration dynamics, resulting in a better fit for `K_a`.

**Comment by Oblarg** [comment]
This should be accompanied by minimizing the velocity filtering in the smart motor controller project templates.

**Comment by pietroglyph** [comment]
Just a note about the uniform data format: the drive logger runs an extra track width test, and as a result it has an extra set of data for that test. Any additional unification of the data format will need to manage this reality. I might have a different picture of what this effort looks like than you do, but I would like to point out that there are 4 separate logger GUIs and 16 different templates—moving complexity from the loggers to the templates moves the duplication from 4 to 16 places unless we're careful.
