### ISSUE TITLE
Fonts not rendering on Mac

### ISSUE THREAD

**Issue by kushagharahi** [wpilibsuite/frc-characterization#123]
Installed via `pip3` 
I get the following error: `Unable to revert mtime: /Library/Fonts` when running `frc-characterization drive new`
This is how it renders:
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/3326002/76178199-97e27700-6184-11ea-830f-76e5e6aad6c0.png">

**Comment by auscompgeek** [comment]
Is this a duplicate of #46?

**Comment by pietroglyph** [comment]
Looks like it to me… Is @kushagharahi running pre-Catalina macOS? If they are then it’s almost certainly the same bug.

(The workaround is switching out of dark mode, btw.)

**Comment by kushagharahi** [comment]
Yes this is a duplicate of #46. I tried to make sure there weren't dups, but I failed.

Thanks for the help guys! I love the tool.
