### ISSUE TITLE
Should use Leader/Follower terminology, rather then Master/Slave

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/frc-characterization#127]

**Comment by Piphi5** [comment]
What is the advantage of changing the terminology from the ones used by the motor controllers (Talon SRX, Spark Max, etc.)?

**Comment by calcmogul** [comment]
The Spark MAX actually uses leader/follower, not master/slave.

Leader/follower more clearly describes the relationship between the motor controllers than master/slave does to someone who isn't already familiar with the jargon.

**Comment by Piphi5** [comment]
Ok, I'll add that to the refactor once the functionality is stable.

**Comment by Starlight220** [comment]
would find/replace be sufficient for this, or is something more advanced needed?
