### ISSUE TITLE
Track-width computation doesn't account for wheel circumference

### ISSUE THREAD

**Issue by chauser** [wpilibsuite/frc-characterization#166]
In data_analyzer.py, calcTrackWidth returns the track width in units of wheel revolutions, not the project unit, as can be seen by considering that d_left and d_right are directly computed from table entries that are measured in revolutions in the self.stored_data table.
I noticed this in characterizing a Romi where the calculated track width was about 0.67m. For a more usual robot the scale of the error would be about a factor of 2 (too large, as 6" wheels have about a 0.5m circumference). I wonder if this behind the remark in https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-characterization/characterization-routine.html that  "the empirical trackwidth calculated by frc-characterization may be significantly different from the real trackwidth (e.g., off by a factor of 2)."?

**Comment by calcmogul** [comment]
> 6" wheels have about a 0.5m circumference

Six inches corresponds to 0.1524 meters, so what you're saying here doesn't make sense.

**Comment by chauser** [comment]
.1524m (diameter) * pi = 0.478m (circumference)
In the pre-processed tables that are used for other computations in the analyzer the raw data in the self.stored_data table are multiplied by self.units_per_rot; that does not seem to be happening for the track width computation. The .json file of characterization data ends with 
```
    "test": "Drivetrain",
    "units": "Rotations",
    "unitsPerRotation": 1.0
}
```
so at least in the data I'm using it is clear that an adjustment needs to be made.

**Comment by calcmogul** [comment]
@Piphi5 Looks like we missed this in the unit conversion rewrite.

**Comment by chauser** [comment]
I guess a stronger bit of evidence is that regardless of what unit you choose in the data analyzer, the track width output is always the same.

**Comment by Piphi5** [comment]
I'll open a PR soon

**Comment by sciencewhiz** [comment]
The reason for the note in the docs is because how easily a robot turns may vary quite a bit from the theoretical calculation a lot due to things like wheel type (ie its harder to turn with wide sticky pneumatic wheels).
