### ISSUE TITLE
Failed to generate project, "Exception in Tkinter callback"

### ISSUE THREAD

**Issue by FireShredder24** [wpilibsuite/frc-characterization#183]
When I hit "Generate Project", [this error](https://pastebin.com/YJqnKdrw) appears in the terminal.
As you can see if you read the [config file](https://pastebin.com/RtQ4TX8E), our robot uses 4 Falcon 500 motors, 2 on each side.  I used the CTRE control type, drivetrain project type, and team number 4999.  The unit was meters, and UPR was 0.044537, to reflect the wheel diameter and gearing.

**Comment by sciencewhiz** [comment]
The inverted fields need to be arrays with two values also.

**Comment by FireShredder24** [comment]
I just tried that.  Similar error, but slightly different code in the last line

**Comment by Daltz333** [comment]
Controller types need to be quoted

**Comment by FireShredder24** [comment]
Thanks, it worked that time!
