### ISSUE TITLE
Unable to generate project

### ISSUE THREAD

**Issue by ThiessenLouisG** [wpilibsuite/frc-characterization#185]
I'm trying to make a characterization project for my teams robot. When I try to generate the project I get the error message: Unable to generate project - config might be bad. Details: Permission error (13, 'Permission denied') 

[CLI returns](https://github.com/ThiessenLouisG/6044RobotCode2021/blob/main/err.txt)
[Project file](https://github.com/ThiessenLouisG/6044RobotCode2021/blob/main/robotconfig.py)

**Comment by pietroglyph** [comment]
Right now the tool only works with Python 3.7.

**Comment by ThiessenLouisG** [comment]
I have python3.7 , but my system wants to run it with 3.9. Does anyone know how to avoid this?

**Comment by auscompgeek** [comment]
If you install it using python3.7, it'll run using python3.7.

**Comment by ThiessenLouisG** [comment]
I've come to the conclusion that unless you have python 3.7 as your primary python installation this tool is unusable. My primary python installation was 3.9, and even by uninstalling 3.9 and doing a fresh reinstall of 3.7 was unsuccessful. Multiple errors confused the installation and use to the point of python, pip, and the tool being FUBAR. Please extend support to the newest python versions, or provide sufficient documentation on downgrading/upgrading and installation.

**Comment by Daltz333** [comment]
We do have Python 3.7 explicitly listed in the installation documentation.

**Comment by Piphi5** [comment]
> We do have Python 3.7 explicitly listed in the installation documentation. 

I think the suggestion was to have more explicit documentation on how to downgrade python for those who don't know how to do so.

**Comment by ThiessenLouisG** [comment]
> I think the suggestion was to have more explicit documentation on how to downgrade python for those who don't know how to do so.

Exactly. I've tried everything I could do based off hours of research to no avail. If there is a way to downgrade that I am not aware about I greatly encourage the devs to share.

**Comment by Daltz333** [comment]
Windows is quite easy. Just run the uninstalled. We can link instructions in documentation, but frc-char doesn't have much lifespan left, as we are creating a C++ equivalent with imgui.
